sudo: required
services:
  - docker

before_install:
  - docker build -t duynvh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true duynvh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-362638162167"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"